services:
    frontend:
        build:
            context: ./Dashboard/frontend/frontend 
            dockerfile: Dockerfile
        env_file:
            - path: .env
              required: false
        working_dir: /app
        ports:
            - "80:80"
        restart: always
        depends_on:
            backend:
                condition: service_started

    backend:
        image: golang:1.26-bookworm
        env_file:
            - path: ./Infrastructure/.env
              required: false
            - path: .env
              required: false
        volumes:
            - ./Dashboard/backend:/app
            - go_pkg_cache:/go/pkg
        working_dir: /app
        environment:
            DASHBOARD_CREDS_PATH: dashboard.creds
            TEST_CREDS_PATH: admin_test.creds
            CA_PEM_PATH: ca.pem
        command: sh -c "go mod download && go build -o backend main.go && ./backend"
        depends_on:
            timescale: 
                condition: service_healthy
            cloud-db: 
                condition: service_healthy
            nats:
                condition: service_started

    gateway:
        image: golang:1.26-bookworm
        volumes:
            - ./Gateway:/app
            - go_pkg_cache:/go/pkg
        working_dir: /app
        env_file:
            - path: ./Infrastructure/.env
              required: false
        environment:
            TEST_CREDS_PATH: admin_test.creds
            GATEWAY_BASE_CREDS_PATH: base.creds
            CA_PEM_PATH: ca.pem
        command: sh -c "go mod download && cd cmd && go build -o gateway && ./gateway"
        depends_on:
            timescale:
                condition: service_healthy
            nats: 
                condition: service_started

    dataconsumer:
        image: golang:1.26-bookworm
        volumes:
            - ./DataConsumer:/app
            - go_pkg_cache:/go/pkg
        working_dir: /app
        env_file:
            - path: ./Infrastructure/.env
              required: false
        environment:
            DATA_CONSUMER_CREDS_PATH: data_consumer.creds
            DATA_CONSUMER_TEST_CREDS_PATH: admin_test.creds
            DATA_CONSUMER_CA_PEM_PATH: ca.pem
        command: sh -c "go mod download && cd cmd && go build -o dataconsumer && ./dataconsumer"
        depends_on:
            timescale:
                condition: service_healthy
            nats:
                condition: service_started

include:
  - path: ./Infrastructure/docker-compose.yml

volumes:
  frontend_node_modules:
  go_pkg_cache: